/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ServiceTest {
@Test public void testCreate() {
        Service service = new Service("TESTNAME", "http://TESTURL.se");
        assertNotNull("service should have a name", service.getName());
        assertNotNull("service should have a url", service.getURL());
        assertNotNull("service should have an assigned id", service.getID());
        assertNotNull("service should have an assigned id", service.getIDAsString());
        assertNotNull("service should have a status", service.getStatus());
        assertNotNull("service should have a lastCheck", service.getLastCheck());
        assertNotNull("service should be able to return json", service.toJSON());

        Service serviceCopy = new Service(service.getIDAsString(), service.getName(),
        service.getURL(), service.getStatus(), service.getLastCheck());
        assertEquals("service and serviceCopy name did not match", service.getName(), serviceCopy.getName());
        assertEquals("service and serviceCopy url did not match", service.getURL(), serviceCopy.getURL());
        assertEquals("service and serviceCopy id did not match", service.getID(), serviceCopy.getID());
        assertEquals("service and serviceCopy id string did not match", service.getIDAsString(), serviceCopy.getIDAsString());
        assertEquals("service and serviceCopy status did not match", service.getStatus(), serviceCopy.getStatus());
        assertEquals("service and serviceCopy lastCheck did not match", service.getLastCheck(), serviceCopy.getLastCheck());
        assertEquals("service and serviceCopy json did not match", service.toJSON(), serviceCopy.toJSON());
        assertEquals("service and serviceCopy host did not match", service.getHost(), serviceCopy.getHost());

        String date = "2000-01-01 13:37";
        service.setChecked(date);
        assertNotEquals("service date was not changed", service.getLastCheck(), serviceCopy.getLastCheck());
        serviceCopy.setChecked(date);
        serviceCopy.setCheckedNow();
        assertNotEquals("serviceCopy was not changed to current date/time", service.getLastCheck(), serviceCopy.getLastCheck());
        serviceCopy.setChecked(date);
        assertEquals("service and serviceCopy date did not match", service.getLastCheck(), serviceCopy.getLastCheck());

        service.setStatus(true);
        assertNotEquals("service status was not changed", service.getStatus(), serviceCopy.getStatus());
        serviceCopy.setStatus(true);
        assertEquals("service and serviceCopy status did not match", service.getStatus(), serviceCopy.getStatus());
}
}
