/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.Date;
import io.vertx.core.Vertx;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public String getTime() {
      Date d = new Date();
      return "[" + d.toLocaleString() + "]: ";
    }

    public void startTestServer() {
      Vertx.vertx()
      .createHttpServer()
      .requestHandler(req -> req.response().end("Hello World!"))
      .listen(8080, handler -> {
        if (handler.succeeded()) {
          System.out.println(getTime() + "http://localhost:8080/");
        } else {
          System.err.println(getTime() + "Failed to listen on port 8080");
        }
      });
    }

    public void startServer() {
      Vertx.vertx()
      .createHttpServer()
      .requestHandler(req -> req.response().end(getResponse()))
      .listen(8080, handler -> {
        if (handler.succeeded()) {
          System.out.println(getTime() + "http://localhost:8080/");
        } else {
          System.err.println(getTime() + "Failed to listen on port 8080");
        }
      });
    }

    public String getResponse() {
      return "Hello World!";
    }

    public static void main(String[] args) {
        App app = new App();
        app.startServer();
    }
}
